# Generated by Django 4.0.6 on 2022-07-14 15:46

from django.db import migrations, models
import root.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('org_name', models.CharField(max_length=255)),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='organization/images/')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='organization/images/')),
                ('website', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('company_motto', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('primary_contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_contact_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_support_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_support_company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_support_contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_support_contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('google_map_url', models.URLField(blank=True, null=True)),
                ('apple_map_url', models.URLField(blank=True, null=True)),
                ('google_play_store_url', models.URLField(blank=True, null=True)),
                ('apple_app_store_url', models.URLField(blank=True, null=True)),
                ('huawei_app_gallery_url', models.URLField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('footers', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(root.utils.SingletonModel, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
