# Generated by Django 4.0.6 on 2023-05-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailSendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.mailrecipient')),
            ],
        ),
        migrations.CreateModel(
            name='EndDayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('terminal', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndDayDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('net_sales', models.FloatField()),
                ('vat', models.FloatField()),
                ('total_discounts', models.FloatField()),
                ('cash', models.FloatField()),
                ('credit', models.FloatField()),
                ('credit_card', models.FloatField()),
                ('mobile_payment', models.FloatField()),
                ('complimentary', models.FloatField()),
                ('start_bill', models.CharField(max_length=20)),
                ('end_bill', models.CharField(max_length=20)),
                ('total_void_count', models.IntegerField()),
                ('date_time', models.CharField(max_length=100, null=True)),
                ('food_sale', models.FloatField()),
                ('beverage_sale', models.FloatField()),
                ('others_sale', models.FloatField()),
                ('no_of_guest', models.IntegerField()),
                ('terminal', models.CharField(max_length=10, null=True)),
                ('total_sale', models.FloatField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
