# Generated by Django 4.0.6 on 2022-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='primary_contact_company_email',
            new_name='company_contact_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='company_motto',
            new_name='company_contact_number',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='copyright',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='primary_contact_number',
            new_name='contact_person_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='apple_app_store_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='apple_map_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='fav_icon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='footers',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='google_map_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='google_play_store_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='huawei_app_gallery_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='primary_support_company_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='primary_support_contact_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_contact_company_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_contact_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_support_company_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_support_contact_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PAN/VAT Number'),
        ),
    ]
