# Generated by Django 4.0.6 on 2023-06-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_mailrecipient_mailsendrecord_enddayrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='beverage_sale',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='food_sale',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='no_of_guest',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='others_sale',
        ),
        migrations.RemoveField(
            model_name='enddaydailyreport',
            name='total_void_count',
        ),
    ]
