# Generated by Django 4.0.6 on 2022-07-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
