# Generated by Django 4.0.6 on 2022-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
