# Generated by Django 4.0.6 on 2022-08-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='current_fiscal_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
