# Generated by Django 4.0.6 on 2022-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_branch_current_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='current_fiscal_year',
        ),
        migrations.AddField(
            model_name='organization',
            name='current_fiscal_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
