# Generated by Django 4.0.6 on 2022-08-05 04:07

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_branch_current_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default=organization.models.get_default_uuid, max_length=255, unique=True),
        ),
    ]
