# Generated by Django 4.0.6 on 2022-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_bank_qr',
            field=models.ImageField(blank=True, null=True, upload_to='organization/images/'),
        ),
    ]
