# Generated by Django 4.0.6 on 2023-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_slug_remove_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Product Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Category Slug'),
            preserve_default=False,
        ),
    ]
