# Generated by Django 4.0.6 on 2023-05-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_mailrecipient_mailsendrecord_enddayrecord_and_more'),
        ('product', '0003_itemreconcilationapiitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStockTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('opening', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('wastage', models.IntegerField(default=0)),
                ('returned', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('closing', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('discrepancy', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
            options={
                'unique_together': {('branch', 'product', 'date')},
            },
        ),
    ]
