# Generated by Django 4.0.6 on 2023-01-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_barcode_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMultiprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('product_price', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'product_multiprice',
                'managed': False,
            },
        ),
    ]
