# Generated by Django 4.0.6 on 2022-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_agent_billitem_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, default='Cash', max_length=255, null=True),
        ),
    ]
