# Generated by Django 4.0.6 on 2023-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_conflictbillnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fiscal_year',
            field=models.CharField(default='79/80', max_length=20),
            preserve_default=False,
        ),
    ]
