# Generated by Django 4.0.6 on 2022-07-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branch'),
        ('bill', '0004_bill_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch'),
        ),
    ]
