# Generated by Django 4.0.6 on 2022-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_bill_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='terminal',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
