# Generated by Django 4.0.6 on 2022-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_bill_service_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablReturnEntry',
            fields=[
                ('idtblreturnEntry', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_date', models.CharField(max_length=20, null=True)),
                ('bill_no', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_pan', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('no_tax_sales', models.FloatField(default=0.0)),
                ('zero_tax_sales', models.FloatField(default=0.0)),
                ('taxable_amount', models.FloatField(null=True)),
                ('tax_amount', models.FloatField(null=True)),
                ('miti', models.CharField(max_length=20, null=True)),
                ('serviced_item', models.CharField(default='Goods', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'idtblreturnEntry',
            },
        ),
        migrations.CreateModel(
            name='TblSalesEntry',
            fields=[
                ('tblSalesEntry', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_date', models.CharField(max_length=20, null=True)),
                ('bill_no', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_pan', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('no_tax_sales', models.FloatField(default=0.0)),
                ('zero_tax_sales', models.FloatField(default=0.0)),
                ('taxable_amount', models.FloatField(null=True)),
                ('tax_amount', models.FloatField(null=True)),
                ('miti', models.CharField(max_length=20, null=True)),
                ('serviced_item', models.CharField(default='Goods', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'tblSalesEntry',
            },
        ),
        migrations.CreateModel(
            name='TblTaxEntry',
            fields=[
                ('idtbltaxEntry', models.IntegerField(primary_key=True, serialize=False)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('bill_no', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_pan', models.CharField(max_length=200, null=True)),
                ('bill_date', models.DateField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('taxable_amount', models.FloatField(null=True)),
                ('tax_amount', models.FloatField(null=True)),
                ('is_printed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('printed_time', models.CharField(max_length=20, null=True)),
                ('entered_by', models.CharField(max_length=20, null=True)),
                ('printed_by', models.CharField(max_length=20, null=True)),
                ('is_realtime', models.BooleanField(default=False)),
                ('sync_with_ird', models.BooleanField(default=True)),
                ('payment_method', models.CharField(default='Cash', max_length=20, null=True)),
                ('vat_refund_amount', models.FloatField(default=0.0)),
                ('transaction_id', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbltaxentry',
            },
        ),
    ]
