# Generated by Django 4.0.6 on 2022-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_tablreturnentry_tblsalesentry_tbltaxentry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablreturnentry',
            table='tblreturnentry',
        ),
    ]
