# Generated by Django 4.0.6 on 2022-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_bill_agent_name_bill_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablreturnentry',
            name='bill_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tblsalesentry',
            name='bill_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbltaxentry',
            name='bill_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
