# Generated by Django 4.0.6 on 2022-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_alter_tablreturnentry_bill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablreturnentry',
            name='idtblreturnEntry',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblsalesentry',
            name='tblSalesEntry',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltaxentry',
            name='idtbltaxEntry',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
