# Generated by Django 4.0.6 on 2022-08-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_alter_tablreturnentry_idtblreturnentry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablreturnentry',
            old_name='no_tax_sales',
            new_name='NoTaxSales',
        ),
        migrations.RenameField(
            model_name='tablreturnentry',
            old_name='serviced_item',
            new_name='ServicedItem',
        ),
        migrations.RenameField(
            model_name='tablreturnentry',
            old_name='zero_tax_sales',
            new_name='ZeroTaxSales',
        ),
        migrations.RenameField(
            model_name='tblsalesentry',
            old_name='no_tax_sales',
            new_name='NoTaxSales',
        ),
        migrations.RenameField(
            model_name='tblsalesentry',
            old_name='serviced_item',
            new_name='ServicedItem',
        ),
        migrations.RenameField(
            model_name='tblsalesentry',
            old_name='zero_tax_sales',
            new_name='ZeroTaxSales',
        ),
        migrations.AlterField(
            model_name='tbltaxentry',
            name='is_active',
            field=models.CharField(default='Yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbltaxentry',
            name='is_printed',
            field=models.CharField(default='Yes', max_length=20),
        ),
    ]
