# Generated by Django 4.0.6 on 2022-08-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_rename_no_tax_sales_tablreturnentry_notaxsales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltaxentry',
            name='is_realtime',
            field=models.CharField(default='Yes', max_length=20),
        ),
    ]
