# Generated by Django 4.0.6 on 2022-08-04 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_alter_tbltaxentry_is_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='transaction_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbltaxentry',
            name='sync_with_ird',
            field=models.CharField(default='Yes', max_length=20),
        ),
    ]
