# Generated by Django 4.0.6 on 2022-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_alter_tablreturnentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltaxentry',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
