# Generated by Django 4.0.5 on 2022-08-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_tbltaxentry_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltaxentry',
            name='reason',
        ),
        migrations.AddField(
            model_name='tablreturnentry',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
