# Generated by Django 4.0.6 on 2022-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0018_remove_tbltaxentry_reason_tablreturnentry_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablreturnentry',
            name='exemptedSales',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tablreturnentry',
            name='export',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tablreturnentry',
            name='exportCountry',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tablreturnentry',
            name='exportDate',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tablreturnentry',
            name='exportNumber',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='exemptedSales',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='export',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='exportCountry',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='exportDate',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='exportNumber',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
