# Generated by Django 4.0.6 on 2022-08-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_tablreturnentry_exemptedsales_tablreturnentry_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablreturnentry',
            name='unit',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='tblsalesentry',
            name='unit',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='tbltaxentry',
            name='unit',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
