# Generated by Django 4.0.6 on 2022-12-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoscountTabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=200)),
                ('dicount_type', models.CharField(choices=[('PCT', 'Percentage'), ('FLAT', 'Flat'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=200)),
                ('discount_amount', models.FloatField()),
            ],
        ),
    ]
