# Generated by Django 4.0.6 on 2022-12-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoscountTabe',
            new_name='DiscountTabe',
        ),
    ]
