# Generated by Django 4.0.6 on 2022-12-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_rename_doscounttabe_discounttabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttabe',
            name='dicount_type',
            field=models.CharField(choices=[('PCT', 'Percentage'), ('FLAT', 'Flat')], default='PCT', max_length=200),
        ),
    ]
