# Generated by Django 4.0.6 on 2022-12-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_discounttabe_dicount_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountTabe',
            new_name='DiscountTable',
        ),
    ]
