# Generated by Django 4.0.6 on 2022-12-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_rename_discounttabe_discounttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounttable',
            old_name='dicount_type',
            new_name='discount_type',
        ),
    ]
