# Generated by Django 4.0.6 on 2023-02-08 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_alter_discounttable_discount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='discounttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discounttable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discounttable',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discounttable',
            name='sorting_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discounttable',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discounttable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
