# Generated by Django 4.0.6 on 2023-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_asset_assetpurchase_assetpurchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assetpurchase',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Credit Card', 'Credit Card'), ('Mobile Payment', 'Mobile Payment'), ('Complimentary', 'Complimentary')], max_length=30),
        ),
    ]
