# Generated by Django 4.0.6 on 2023-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_productpurchase_purchase_productpurchase_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
