# Generated by Django 4.0.6 on 2023-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_accountproducttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciation_pool',
            field=models.CharField(choices=[('A', '5%'), ('B', '25%'), ('C', '30%'), ('D', '15%')], default='A', max_length=5),
            preserve_default=False,
        ),
    ]
