# Generated by Django 4.0.6 on 2023-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill_date',
            field=models.DateField(),
        ),
    ]
