# Generated by Django 4.0.6 on 2023-04-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_asset_depreciation_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='depreciation_pool',
        ),
    ]
