# Generated by Django 4.0.6 on 2023-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_productpurchase_item_total_productpurchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='grand_amount',
            new_name='non_taxable_amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_in_words',
            field=models.CharField(default='One Hundred', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(default='CASH', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
