# Generated by Django 4.0.6 on 2023-04-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_depreciationpool'),
        ('purchase', '0005_assetpurchaseitem_depreciation_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpurchaseitem',
            name='depreciation_pool',
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.depreciationpool'),
        ),
    ]
