# Generated by Django 4.0.6 on 2023-02-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_tblpurchaseentry_tblpurchasereturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchaseentry',
            old_name='no_tax_purchase',
            new_name='non_tax_purchase',
        ),
        migrations.RenameField(
            model_name='tblpurchasereturn',
            old_name='no_tax_purchase',
            new_name='non_tax_purchase',
        ),
        migrations.AlterField(
            model_name='tblpurchaseentry',
            name='bill_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tblpurchasereturn',
            name='bill_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
