# Generated by Django 4.0.6 on 2023-02-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_no_tax_purchase_tblpurchaseentry_non_tax_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
