# Generated by Django 4.0.6 on 2023-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_remove_purchase_purchase_date_purchase_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
