# Generated by Django 4.0.6 on 2022-07-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branch'),
        ('user', '0004_customer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
    ]
