# Generated by Django 4.0.6 on 2023-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbljournalentry',
            name='journal_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
