# Generated by Django 4.0.6 on 2023-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchart',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsubledger',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
