# Generated by Django 4.0.6 on 2023-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciation',
            name='miti',
            field=models.CharField(max_length=15),
        ),
    ]
