# Generated by Django 4.0.6 on 2023-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountchart_is_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchart',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountsubledger',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
