# Generated by Django 4.0.6 on 2023-03-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_tbljournalentry_journal_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_ledger_name', models.CharField(max_length=100, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_editable', models.BooleanField(default=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
