# Generated by Django 4.0.6 on 2023-05-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciation',
            name='fiscal_year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
