# Generated by Django 4.0.6 on 2023-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_depreciation_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcrjournalentry',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tbldrjournalentry',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tbljournalentry',
            name='journal_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
