# Generated by Django 4.0.6 on 2023-04-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountsubledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrjournalentry',
            name='sub_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsubledger'),
        ),
        migrations.AddField(
            model_name='tbldrjournalentry',
            name='sub_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountsubledger'),
        ),
    ]
