# Generated by Django 4.0.6 on 2023-05-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_tblcrjournalentry_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciation',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountledger'),
        ),
    ]
