# Generated by Django 4.0.6 on 2023-04-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tblcrjournalentry_sub_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubledger',
            name='sub_ledger_name',
            field=models.CharField(max_length=100),
        ),
    ]
