# Generated by Django 4.0.6 on 2023-02-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_journal_entry_tblcrjournalentry_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcrjournalentry',
            old_name='description',
            new_name='journal_entry',
        ),
        migrations.RenameField(
            model_name='tbldrjournalentry',
            old_name='description',
            new_name='journal_entry',
        ),
    ]
