# Generated by Django 4.0.6 on 2023-04-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_accountsubledger_sub_ledger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('credit_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger', to='accounting.accountledger')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='accounting.accountledger')),
                ('sub_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accountsubledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
