# Generated by Django 4.0.6 on 2023-03-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_rename_description_tblcrjournalentry_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLedgerHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='accounting.accountsubledger', verbose_name='Direct Expenses')),
                ('direct_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_income', to='accounting.accountsubledger', verbose_name='Direct Income')),
                ('fixed_assets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='accounting.accountsubledger', verbose_name='Fixed Assets')),
                ('indirect_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirect_expenses', to='accounting.accountsubledger', verbose_name='Indirect Expenses')),
                ('indirect_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirect_income', to='accounting.accountsubledger', verbose_name='Indirect Income')),
                ('loans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='accounting.accountsubledger', verbose_name='Loans')),
                ('purchase_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_accounts', to='accounting.accountsubledger', verbose_name='Purchase Accounts')),
                ('sales_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_accounts', to='accounting.accountsubledger', verbose_name='Sales Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
