# Generated by Django 4.0.6 on 2023-05-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_depreciation_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_name', models.CharField(max_length=200, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value_changed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountchart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
