# Generated by Django 4.0.6 on 2023-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=3)),
                ('percentage', models.SmallIntegerField()),
            ],
        ),
    ]
