# Generated by Django 4.0.6 on 2023-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_cumulativeledger_ledger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeledger',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cumulativeledger',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
