# Generated by Django 4.0.6 on 2023-04-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_depreciationpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='depreciation_pool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.depreciationpool'),
        ),
    ]
