# Generated by Django 4.0.6 on 2023-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountledger_depreciation_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountledger',
            name='depreciation_pool',
        ),
    ]
